version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - todo_backend_database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: damarkevich/todo_backend:latest
    restart: always
    volumes:
      - todo_backend_static:/app/static/
      - todo_backend_media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../todo_frontend
      dockerfile: Dockerfile
    volumes:
      - ../todo_frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - todo_backend_static:/var/html/static/
      - todo_backend_media:/var/html/media/
    depends_on:
      - frontend

volumes:
  todo_backend_database:
  todo_backend_static:
  todo_backend_media:
