# Generated by Django 4.1.7 on 2023-03-30 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_assigned_to_alter_task_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Enter due date', verbose_name='Due date'),
        ),
    ]
