# Generated by Django 4.1.7 on 2023-03-24 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_options_task_author_task_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Appoint responsible', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for_user', to=settings.AUTH_USER_MODEL, verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Enter task author', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
